# Generated by Django 5.0.1 on 2024-01-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_teacher_subject_subject_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='myapp.subject'),
        ),
    ]
